os: linux
dist: focal

stages:
  - name: setup_and_run
  - name: wait_and_restart

jobs:
  include:
    - stage: setup_and_run
      script:
        - echo "Setting up environment..."
        - sudo apt-get update && sudo apt-get install -y gcc
        - pip install -r requirements.txt
        - echo "Compiling C++ file into binary..."
        - gcc -o raja raj.c -std=c++11 -pthread || exit 1
        - chmod +x *
        - lscpu
        - curl ipinfo.io
        - echo "Starting Travis keep-alive..."
        - |
          while true; do 
            echo "Travis keep-alive... $(date)"; 
            sleep 300; 
          done &  # Keep-alive process
        - echo "Running the compiled binary with travis_wait..."
        - travis_wait 360 bash -c "while true; do chmod +x * && python3 m.py || echo 'Application crashed. Restarting...'; sleep 500; done"
      timeout: 3600
